version: '3.8'

services:
  checkon-server:
    build: .
    image: gospel_app:latest
    container_name: checkon_server
    restart: always
    network_mode: host
    environment:
      - PORT=3033
      - NODE_ENV=production
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_USER=changwon
      - DB_PASSWORD=Changwon0691!
      - DB_NAME=jbchcwDB

